name: Build Go Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_NAME: image-mover-util
  MAIN_PACKAGE_PATH: ../../src/

jobs:
  build:
    # Use a matrix strategy to build for multiple platforms
    strategy:
      matrix:
        # Define the platforms you want to build for
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            os: linux
            arch: amd64
          - platform: macos-latest
            os: darwin
            arch: amd64
          - platform: windows-latest
            os: windows
            arch: amd64

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23' # Or your desired Go version

    # This step is only necessary for Linux builds
    - name: Install Linux dependencies for Gio
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: Build application
      # Set environment variables for cross-compilation
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        # For Windows, we want the executable to have a .exe extension
        if [ "${{ matrix.os }}" = "windows" ]; then
          go build -v -o ${{ env.APP_NAME }}.exe ${{ env.MAIN_PACKAGE_PATH }}
        else
          go build -v -o ${{ env.APP_NAME }} ${{ env.MAIN_PACKAGE_PATH }}
        fi
      # We run the build from within the 'src' directory
      working-directory: src

    - name: Test Go code
      run: go test -v ./...
      working-directory: src

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # The name of the artifact in the GitHub UI
        name: ${{ env.APP_NAME }}-${{ matrix.os }}-${{ matrix.arch }}
        # The path to the file(s) to upload.
        # We look inside the 'src' directory for our compiled app.
        path: src/${{ env.APP_NAME }}${{ matrix.os == 'windows' && '.exe' || '' }}
